# Your project's server will run on localhost:xxxx at this port
PORT: 3000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "src/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"  
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
    - "!src/assets/{img,js,scss}/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    # - "bower_components/foundation-sites/scss"
    # - "bower_components/motion-ui/src"
  # Paths to JavaScript libraries, which are combined into one file
  javascript:
    # Paths to your own project code are here
    - "src/assets/js/!(app).js"
    - "src/assets/js/app.js"
    # Libraries required by Foundation
    # - "bower_components/jquery/dist/jquery.js"
    # - "bower_components/what-input/what-input.js"
    # Core Foundation files
    # - "bower_components/foundation-sites/js/foundation.core.js"
    # - "bower_components/foundation-sites/js/foundation.util.*.js"
